#!/bin/bash
# Remember when we looked at variables we discovered $RANDOM will return a 
# random number. This number is between 0 and 32767 which is not always the 
# most useful. Let's write a script which will use this variable and some 
# arithmetic (hint: play with modulus) to return a random number between 0 
# and 100.
zeroto32767=$RANDOM
echo Random number = $zeroto32767
echo mod by 100 = $(($zeroto32767%100))

#Now let's play with the previous script. Modify it so that you can specify
#as a command line argument the upper limit of the random number. Can you 
#make it so that a lower limit can be specified also? eg. if I ran
#./random.sh 10 45 it would only return random numbers between 10 and 45.
if [ "$1" ] && [ "$2" ] 
then
  RANDCOMMARG=$(($1 + RANDOM%(1+$2-$1)))
  echo only random number between $1 and $2 = $RANDCOMMARG
fi
